pyDatabaseOps/DatabaseOperations.py,sha256=mk_h38kWxdILFVrJWUaQ3BdV09qCrbHpUWy00V2an1g,9994
pyDatabaseOps/UserDefinedExceptions.py,sha256=8qf6NSmdEgOzLCWsS9DxqeNmYyTVpBVWHu19sO-n3zg,634
pyDatabaseOps/__init__.py,sha256=seRyfh1ud_nC5O8Qk6RZ-kDz3WmHBI4uowm9Gg78BZM,126
pydbops-0.0.2.dist-info/LICENSE,sha256=JVWtqQQAXfEo3ICSfGf0topveOskoTIK5YCRj08vBqE,1094
pydbops-0.0.2.dist-info/METADATA,sha256=dMTxuyljkLsodGmhszUdyvQe9QIjnHknvAmR0EU1d6o,852
pydbops-0.0.2.dist-info/WHEEL,sha256=G16H4A3IeoQmnOrYV4ueZGKSjhipXx8zc8nu9FGlvMA,92
pydbops-0.0.2.dist-info/top_level.txt,sha256=uzJGRIoshDszA3sxRMbGgVk85Vvj-rJi1yjHsxgnSJc,14
pydbops-0.0.2.dist-info/RECORD,,
